# Generated by Django 4.0.2 on 2022-02-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_file_file_file_filename_alter_ticket_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.TextField(max_length=200),
        ),
    ]
